# Generated by Django 4.2.8 on 2023-12-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='strategy',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='heatmap',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='processed_video',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
